const $=s=>document.querySelector(s);const uniq=a=>[...new Set(a)];
const allSchools=uniq(GROUPS.flatMap(g=>g[3])).sort();$('#schools').innerHTML=allSchools.map(s=>`<option value="${s}">`).join('');
function groupsFor(s){return GROUPS.filter(g=>g[3].includes(s))}
function tags(a){return a.map(x=>`<span class="school-tag">${x}</span>`).join('')}
function areaUI(){const s=$('#resSchool').value.trim(),r=AREA_RULES[s],box=$('#areaBox');if(!r){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<strong>${r.label}</strong><p>${r.text}</p>`+(r.type==='choice'?`<select id="areaChoice">${r.options.map(x=>`<option>${x}</option>`).join('')}</select>`:'')}
$('#resSchool').addEventListener('change',areaUI);$('#resSchool').addEventListener('input',areaUI);
function lookup(){const r=$('#resSchool').value.trim(),a=$('#attSchool').value.trim(),rg=groupsFor(r),ag=groupsFor(a),out=$('#basicResult');if(!r||!a||!rg.length||!ag.length){out.className='result empty';out.textContent='입력한 초등학교를 확인해 주세요.';return}const violation=r!==a;let html=`<div class="status ${violation?'warn':'ok'}"><strong>${violation?'학구위반 가능성 확인 필요':'재학학교와 거주지 통학구역 학교 일치'}</strong><br>${violation?'두 학교가 다릅니다. 예외 전학 사유가 아니라면 학구위반 규칙이 적용될 수 있습니다.':'일반적인 거주지 기준 판정 흐름입니다.'}</div>`;html+=`<h3>거주지 기준 후보 중학군(구)</h3>`+rg.map(g=>`<div class="group"><span class="badge">${g[1]}</span><strong>${g[0]}</strong><div class="schools">${tags(g[2])}</div>${g[4]?`<p class="warntext">※ ${g[4]}</p>`:''}</div>`).join('');const ar=AREA_RULES[r];if(ar?.type==='fixed')html+=`<div class="callout"><strong>혼합지원 특례 적용</strong><p>${ar.text}</p><div class="schools">${tags(ar.schools)}</div><p>지원 제한: ${ar.deny.join(', ')}</p></div>`;if(ar?.type==='choice')html+=`<div class="callout"><strong>주소 세부판정 필요</strong><p>${ar.text}. 현재 V2에는 통·리 주소 DB가 없어 이 항목은 자동 확정하지 않습니다.</p></div>`;out.className='result';out.innerHTML=html}
$('#lookup').onclick=lookup;
$('#conditions').innerHTML=SPECIAL.map((x,i)=>`<button class="chip" data-i="${i}">${x[0]}</button>`).join('');
function renderConditions(){const sel=[...document.querySelectorAll('.chip.active')].map(x=>SPECIAL[+x.dataset.i]);$('#followups').innerHTML=sel.flatMap(x=>(FOLLOW[x[0]]||[]).map((q,j)=>`<label class="question"><span>${x[0]} · ${q}</span><select data-cond="${x[0]}" data-q="${j}"><option>확인 필요</option><option>예</option><option>아니오</option></select></label>`)).join('');const out=$('#conditionResult');out.className=sel.length?'result':'result empty';out.innerHTML=sel.length?sel.map(x=>`<div class="plan-item"><strong>${x[0]}</strong><br>${x[1]}</div>`).join(''):'선택한 조건이 없습니다.'}
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{b.classList.toggle('active');renderConditions()});
$('#finalBtn').onclick=()=>{lookup();const r=$('#resSchool').value.trim(),a=$('#attSchool').value.trim(),rg=groupsFor(r),sel=[...document.querySelectorAll('.chip.active')].map(x=>SPECIAL[+x.dataset.i]);let h='<h3>종합 판정</h3>';if(!r||!a||!rg.length){$('#finalResult').className='result empty';$('#finalResult').textContent='먼저 기본정보를 정확히 입력해 주세요.';return}if(r!==a)h+=`<div class="status warn"><strong>학구위반 여부 우선 확인</strong><br>실거주 통학구역 학교와 재학학교가 다릅니다. 적용 제외 사유인지 학교 확인이 필요하며, 학구위반이면 같은 지망에서 정상 지원자 뒤에 배정됩니다.</div>`;const ar=AREA_RULES[r];if(ar?.type==='fixed')h+=`<p><strong>지원가능학교(혼합지원 특례):</strong></p><div class="schools">${tags(ar.schools)}</div>`;else h+=`<p><strong>거주지 기준 중학군(구):</strong> ${rg.map(g=>g[0]).join(' / ')}</p><div class="schools">${tags(uniq(rg.flatMap(g=>g[2])))}</div>`;if(ar?.type==='choice')h+=`<p class="warntext"><strong>확정 보류:</strong> 이 초등학교는 세부 주소에 따라 공동학구가 달라질 수 있으므로 주소 DB 연결 또는 원문 대조가 필요합니다.</p>`;if(sel.length){h+='<h3>개인조건 적용</h3>'+sel.map(x=>`<p><strong>${x[0]}</strong> — ${x[1]}</p>`).join('');if(sel.some(x=>x[0]==='학교폭력 관련'))h+=`<p class="warntext"><strong>규칙 우선순위:</strong> 학교폭력 관련 대상과 다른 우선배정 대상이 동시에 해당하면 학교폭력 관련 원칙을 우선 적용합니다.</p>`}h+=`<div class="callout"><strong>결과 해석</strong><p>위 학교는 '실제 배정 예상학교'가 아니라 현재 입력조건에서 확인되는 지원/배정 범위입니다. 일반 중학군의 최종 학교는 사이트에서 예측할 수 없습니다.</p></div>`;$('#finalResult').className='result';$('#finalResult').innerHTML=h};
function renderPlan(type){const data=type==='general'?GENERAL:type==='mixed'?MIXED:type==='special'?SPECIAL:REASSIGN;$('#plan').innerHTML=data.map(x=>`<div class="plan-item"><strong>${x[0]}</strong><br>${x.slice(1).join(' · ')}</div>`).join('')}renderPlan('general');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPlan(b.dataset.tab)});
